CSC-Assignment-2/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using CSC_Assignment_2.Areas.HelpPage.ModelDescriptions;
using CSC_Assignment_2.Areas.HelpPage.Models;

namespace CSC_Assignment_2.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

CSC-Assignment-2/Controllers/SendMailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSC_Assignment_2.Controllers
{
    public class SendMailController : Controller
    {
        // GET: SendMail
        public ActionResult Index()
        {
            ViewBag.Title = "Send Mail Page";
            return View();
        }
    }
}

CSC-Assignment-2/Controllers/UserPhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSC_Assignment_2.Controllers
{
    public class UserPhotosController : Controller
    {
        // GET: UserPhotos
        public ActionResult Index()
        {
            ViewBag.Title = "User Photos Page";
            return View();
        }
    }
}

CSC-Assignment-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="pos-f-t">
        <div class="navbar navbar-light navbar-static-top bg-faded navbar-full">
            <div class="container">
                <button class="navbar-toggler hidden-sm-up collapsed " type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-expanded="false">
                    ☰
                </button>
                <div class="navbar-toggleable-xs collapse" id="exCollapsingNavbar2" aria-expanded="false" style="height: 0px;">
                    @Html.ActionLink("CSC Assignment 2", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            @Html.ActionLink("Gallery", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Profile", null, "Profile", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Private Gallery", "Index", "UserPhotos", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Send Mail", "Index", "SendMail", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Weather", "Index", "Weather", new { area = "" }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            <a href="http://bryan-csc-a1task3.azurewebsites.net/SearchTalent/" class="nav-link">Talents</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("API", "Index", "Help", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Yaowei &amp; Bryan</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        $(".nav a").on("click", function () {
            $(".nav").find(".active").removeClass("active");
            $(this).parent().addClass("active");
        });
    </script>
</body>
</html>